#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "############################ ${LP}GENOMES${NC} ############################"
echo -e "#################################################################"

## medsa
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.12MR

## medtr
./gradlew integrate --stacktrace -Psource=A17.gnm5.MVZ2
./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.2GZ9
./gradlew integrate --stacktrace -Psource=HM004.gnm1.L7PM
./gradlew integrate --stacktrace -Psource=HM010.gnm1.YDPY
./gradlew integrate --stacktrace -Psource=HM022.gnm1.B190
./gradlew integrate --stacktrace -Psource=HM023.gnm1.FFHH
./gradlew integrate --stacktrace -Psource=HM034.gnm1.6VW9
./gradlew integrate --stacktrace -Psource=HM050.gnm1.9JPP
./gradlew integrate --stacktrace -Psource=HM056.gnm1.JBKN
./gradlew integrate --stacktrace -Psource=HM058.gnm1.JVBP
./gradlew integrate --stacktrace -Psource=HM060.gnm1.V7B2
./gradlew integrate --stacktrace -Psource=HM095.gnm1.FBQK
./gradlew integrate --stacktrace -Psource=HM125.gnm1.GFN2
./gradlew integrate --stacktrace -Psource=HM129.gnm1.9HG9
./gradlew integrate --stacktrace -Psource=HM185.gnm1.1G05
./gradlew integrate --stacktrace -Psource=HM324.gnm1.SJSJ
./gradlew integrate --stacktrace -Psource=R108.gnmHiC_1.7RWS
