#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################## ${LP}DESCRIPTIONS${NC} #########################"
echo -e "#################################################################"

## Medicago
./gradlew integrate --stacktrace -Psource=medsa-description
./gradlew integrate --stacktrace -Psource=medtr-description

## others from synteny
./gradlew integrate --stacktrace -Psource=aradu-description
./gradlew integrate --stacktrace -Psource=araip-description
./gradlew integrate --stacktrace -Psource=cajca-description
./gradlew integrate --stacktrace -Psource=glyma-description
./gradlew integrate --stacktrace -Psource=lotja-description
./gradlew integrate --stacktrace -Psource=lupan-description
./gradlew integrate --stacktrace -Psource=phavu-description
./gradlew integrate --stacktrace -Psource=vigan-description
./gradlew integrate --stacktrace -Psource=vigra-description
