#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'
echo -e "#################################################################"
echo -e "############################ ${LP}MINIMINE${NC} ###########################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=Phaseolus-vulgaris-description
./gradlew integrate --stacktrace -Psource=G19833.gnm2.fC0g
./gradlew integrate --stacktrace -Psource=G19833.gnm2.ann1.PB8d

./gradlew integrate --stacktrace -Psource=Cicer-arietinum-description
./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm2.S2FF
./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm2.ann1.9M1L

 ./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K
 ./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K.trees_ML_rooted

./gradlew integrate --stacktrace -Psource=phytozome_10_2.genefam.descriptors

./gradlew integrate --stacktrace -Psource=interpro
./gradlew integrate --stacktrace -Psource=interpro-go

./gradlew integrate --stacktrace -Psource=go
./gradlew integrate --stacktrace -Psource=so
