#!/bin/bash
NC='\033[0m'
LP='\033[1;35m'

for SOURCE in sequence-ontology \
                  gene-ontology \
                  interpro-data-set \
                  interpro-domain-go \
                  pfam-term \
                  PANTHER \
                  plant-ontology \
                  plant-trait-ontology \
                  common-bean-crop-ontology \
                  legume.genefam.fam1.M65K \
                  legume.genefam.fam1.M65K.trees_ML_rooted \
                  phytozome_10_2.genefam.descriptors
do
    echo "####"
    echo -e "#### ${LP}${SOURCE}${NC}"
    echo "####"
    ./gradlew integrate --stacktrace -Psource=$SOURCE
done
