#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################### ${LP}ANNOTATION${NC} ##########################"
echo -e "#################################################################"

## medsa
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.ann1.RKB9

## medtr
./gradlew integrate --stacktrace -Psource=A17.gnm5.ann1_6.L2RX
./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.G3ZY
./gradlew integrate --stacktrace -Psource=HM004.gnm1.ann1.2XTB
./gradlew integrate --stacktrace -Psource=HM010.gnm1.ann1.WV9J
./gradlew integrate --stacktrace -Psource=HM022.gnm1.ann1.6C8N
./gradlew integrate --stacktrace -Psource=HM023.gnm1.ann1.WZN8
./gradlew integrate --stacktrace -Psource=HM034.gnm1.ann1.YR6S
./gradlew integrate --stacktrace -Psource=HM050.gnm1.ann1.GWRX
./gradlew integrate --stacktrace -Psource=HM056.gnm1.ann1.CHP6
./gradlew integrate --stacktrace -Psource=HM058.gnm1.ann1.LXPZ
./gradlew integrate --stacktrace -Psource=HM060.gnm1.ann1.H41P
./gradlew integrate --stacktrace -Psource=HM095.gnm1.ann1.55W4
./gradlew integrate --stacktrace -Psource=HM125.gnm1.ann1.KY5W
./gradlew integrate --stacktrace -Psource=HM129.gnm1.ann1.7FTD
./gradlew integrate --stacktrace -Psource=HM185.gnm1.ann1.GB3D
./gradlew integrate --stacktrace -Psource=HM324.gnm1.ann1.SQH2
./gradlew integrate --stacktrace -Psource=R108.gnmHiC_1.ann1.Y8NH
