#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################### ${LP}POSTPROCESS${NC} #########################"
echo -e "#################################################################"

## IM CORE
./gradlew postprocess --stacktrace -Pprocess=do-sources
./gradlew postprocess --stacktrace -Pprocess=create-utr-references
./gradlew postprocess --stacktrace -Pprocess=create-references
./gradlew postprocess --stacktrace -Pprocess=make-spanning-locations
./gradlew postprocess --stacktrace -Pprocess=create-chromosome-locations-and-lengths
./gradlew postprocess --stacktrace -Pprocess=create-intergenic-region-features
./gradlew postprocess --stacktrace -Pprocess=transfer-sequences
./gradlew postprocess --stacktrace -Pprocess=populate-child-features
./gradlew postprocess --stacktrace -Pprocess=create-gene-flanking-features

## VIEWS AND INDEXES
./gradlew postprocess --stacktrace -Pprocess=create-location-overlap-index
./gradlew postprocess --stacktrace -Pprocess=create-overlap-view
./gradlew postprocess --stacktrace -Pprocess=create-attribute-indexes

## LIS
./gradlew postprocess --stacktrace -Pprocess=lis-populate-genefamily-size
./gradlew postprocess --stacktrace -Pprocess=lis-populate-publications

## DO THESE AFTER UPDATES
./gradlew postprocess --stacktrace -Pprocess=summarise-objectstore
./gradlew postprocess --stacktrace -Pprocess=create-autocomplete-index
./gradlew postprocess --stacktrace -Pprocess=create-search-index

