#!/bin/sh

validate-genome-collection /data/v2/Phaseolus/vulgaris/genomes/G19833.gnm2.fC0g
validate-genome-collection /data/v2/Cicer/arietinum/genomes/CDCFrontier.gnm2.S2FF

validate-annotation-collection /data/v2/Phaseolus/vulgaris/annotations/G19833.gnm2.ann1.PB8d
validate-annotation-collection /data/v2/Cicer/arietinum/annotations/CDCFrontier.gnm2.ann1.9M1L


